version: "3.8"
services:
  storelocator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storelocator-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/storelocatorapi2
      - DOCKER=true
    depends_on:
      - storelocator-db
    networks:
      - storelocator-network

  storelocator-db:
    image: "postgres:latest"
    container_name: storelocator-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storelocatorapi2
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - storelocator-network

networks:
  storelocator-network:
    driver: bridge

volumes:
  pg_data:
