version: "3.8"
services:
  storelocator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storelocator-api
    environment:
      - DATABASE_URL="postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${POSTGRES_PORT}/${DATABASE_NAME}"
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - storelocator-db
    networks:
      - storelocator-network
      - main_network

  storelocator-db:
    image: "postgres:15"
    container_name: storelocator-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - storelocator-network

networks:
  storelocator-network:
    driver: bridge
  main_network:
    name: main_network

volumes:
  pg_data:
