version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/storelocatorapi2
      - DOCKER=true
    depends_on:
      - db
    # networks:
    #   - app-network

    # mounting your local directory into the container
    volumes:
      - .:/app

  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storelocatorapi2
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

# networks:
#   app-network:
#     driver: bridge

volumes:
  pg_data:
