version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/storelocatorapi2
    depends_on:
      - db
    # networks:
    #   - app-network

    # volumes:
    #   - .:/app # maps the current directory (where docker-compose.yml is located) to /app inside the container

  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storelocatorapi2
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

# networks:
#   app-network:
#     driver: bridge

volumes:
  pg_data:
